apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: fda-table-service
  name: fda-table-service
spec:
  ports:
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: fda-table-service
status:
  loadBalancer: {}
