apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: fda-identifier-service
  name: fda-identifier-service
spec:
  ports:
    - name: "9096"
      port: 9096
      targetPort: 9096
  selector:
    io.kompose.service: fda-identifier-service
status:
  loadBalancer: {}
