apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: dbrepo-ui-claim
  name: dbrepo-ui-claim
  namespace: dbrepo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    network-public: "true"
    network-core: "true"
    service: dbrepo-ui
  name: dbrepo-ui
  namespace: dbrepo
spec:
  containers:
    - env:
        - name: BROKER_CONSUMERS
          valueFrom:
            configMapKeyRef:
              key: BROKER_CONSUMERS
              name: env
        - name: BROKER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: BROKER_PASSWORD
              name: env
        - name: BROKER_USERNAME
          valueFrom:
            configMapKeyRef:
              key: BROKER_USERNAME
              name: env
        - name: DEFAULT_ROLES
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_ROLES
              name: env
        - name: ELASTIC_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: ELASTIC_PASSWORD
              name: env
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              key: JWT_EXPIRATION
              name: env
        - name: JWT_ISSUER
          valueFrom:
            configMapKeyRef:
              key: JWT_ISSUER
              name: env
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: JWT_SECRET
              name: env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: env
        - name: MAIL_FROM
          valueFrom:
            configMapKeyRef:
              key: MAIL_FROM
              name: env
        - name: MAIL_REPLY_TO
          valueFrom:
            configMapKeyRef:
              key: MAIL_REPLY_TO
              name: env
        - name: MAIL_VERIFY
          valueFrom:
            configMapKeyRef:
              key: MAIL_VERIFY
              name: env
        - name: METADATA_DB
          valueFrom:
            configMapKeyRef:
              key: METADATA_DB
              name: env
        - name: METADATA_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: METADATA_PASSWORD
              name: env
        - name: METADATA_USERNAME
          valueFrom:
            configMapKeyRef:
              key: METADATA_USERNAME
              name: env
        - name: SHARED_FILESYSTEM
          valueFrom:
            configMapKeyRef:
              key: SHARED_FILESYSTEM
              name: env
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              key: SMTP_HOST
              name: env
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SMTP_PASSWORD
              name: env
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              key: SMTP_PORT
              name: env
        - name: SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SMTP_USERNAME
              name: env
        - name: SUPERUSERS
          valueFrom:
            configMapKeyRef:
              key: SUPERUSERS
              name: env
        - name: TOKEN_MAX
          valueFrom:
            configMapKeyRef:
              key: TOKEN_MAX
              name: env
        - name: WEBSITE
          valueFrom:
            configMapKeyRef:
              key: WEBSITE
              name: env
      image: dbrepo/ui
      name: dbrepo-ui
      ports:
        - containerPort: 3000
      resources:
      volumeMounts:
        - mountPath: /tmp
          name: dbrepo-ui-claim
  hostname: ui
  restartPolicy: OnFailure
  volumes:
    - name: dbrepo-ui-claim
      persistentVolumeClaim:
        claimName: dbrepo-ui-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: dbrepo-ui
  name: dbrepo-ui
  namespace: dbrepo
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    service: dbrepo-ui