# Default values for dbrepo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: test

networkPolicies:
  - networkName: public
  - networkName: userdb

deployments:
  - name: ui
    replicaCount: 1
    servicePort: 3000
    image: dbrepo/ui
    env: 
      - name: API
        value: https://dbrepo1.ec.tuwien.ac.at:9095
    createPVC: true
    persistenceSize: 100Mi
  - name: metadata-service
    replicaCount: 1
    servicePort: 9099
    image: dbrepo/metadata-service
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: docker
    createPVC: false
  - name: metadata-db
    replicaCount: 1
    servicePort: 5432
    image: dbrepo/metadata-db
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: docker
    createPVC: true
    mountPath: /var/lib/postgresql/data
    persistenceSize: 100Mi
  - name: authentication
    replicaCount: 1
    servicePort: 9097
    image: jtaha/k8s-authentication-service
    createPVC: false
  - name: broker
    replicaCount: 1
    servicePort: 5672
    image: jtaha/k8s-broker-service
    env:
      - name: BROKER_CONSUMERS
        value: "3"
      - name: BROKER_PASSWORD
        value: pass
      - name: BROKER_USERNAME
        value: user
    createPVC: true
    mountPath: /var/lib/rabbitmq
    persistenceSize: 100Mi
  - name: discovery
    replicaCount: 1
    servicePort: 9090
    image: jtaha/k8s-discovery-service
    createPVC: false
  - name: gateway
    replicaCount: 1
    servicePort: 9095
    image: jtaha/k8s-gateway-service
    createPVC: false

services:
  - name: ui
    ports: 
      - port: 3000
  - name: metadata-service
    ports: 
      - port: 9099
  - name: metadata-db 
    ports: 
      - port: 5432
  - name: authentication
    ports: 
      - port: 9097
  - name: broker
    ports:
      - port: 5672
      - port: 15672
  - name: discovery
    ports:
      - port: 9090
  - name: gateway
    ports:
      - port: 9095

ingress:
  enabled: true
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dbrepo1.ec.tuwien.ac.at
      paths:
        - path: /
          pathType: Prefix
          serviceName: ui
          portNumber: 3000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local