{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
    service: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      service: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        service: {{ .name }}
    spec:
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image }}"
          ports:
            {{- range .ports }}
            - containerPort: {{ .containerPort }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          env:
            {{- toYaml .env | nindent 12 }}
          volumeMounts:
          {{- if .createPVC }}
            - name: volume
              mountPath: {{ default "/tmp" .mountPath }}
          {{- end }}
          {{- if .configMapVolume }}
          {{- with .configMapVolume }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
          {{- end }}
          {{- end }}
      volumes:
      {{- if .createPVC }}
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .name }}-claim
      {{- end }}
      {{- if .configMapVolume }}
      {{- with .configMapVolume }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}

      {{- end }}
      {{- end }}
{{- end }}
