{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    service: {{ .name }}
spec:
  type: {{ default "ClusterIP" .type }}
  ports:
    {{- range .ports }}
    - name: "{{ .port }}"
      port: {{ .port }}
      targetPort: {{ default .port .target }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}
  selector:
    service: {{ .name }}
{{- end }}
