name: Helm-Release

on:
  push:
    branches:
      - main
      - dev
      - helm/ui-test
## REF: https://faun.pub/semantic-version-of-helm-charts-in-github-actions-using-conventional-commits-ce5e0a587ce8
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code                   # Checkout source code
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get specific changed files               
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.5
        with:
          since_last_remote_commit: true
          files: |
            kubernetes/*

      - name: Run chart-releaser
        # if: steps.changed-files-specific.outputs.any_modified == 'true'
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: kubernetes
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"